name: Documentation issue
description: Suggest improvements in the documentation.
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the documentation-related issue or improvement needed.
      placeholder: A clear and concise description of what the problem/enhancement is.
    validations:
      required: true
  - type: textarea
    id: currentdoc
    attributes:
      label: Current Documentation
      description: Link to or describe the current documentation.
    validations:
      required: true
  - type: textarea
    id: desireddoc
    attributes:
      label: Desired Documentation
      description: Describe the desired changes or additions to the documentation.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the documentation issue here.
    validations:
      required: false